[module.hugoVersion]
extended = true
min = "0.124.1"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disabled = false

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"
disabled = false
