[module.hugoVersion]
extended = true
min = "0.56.0"

[[module.imports]]
path = "github.com/dnb-org/libraries/bootstrap5/v2"
disabled = false

[[module.imports]]
path = "github.com/dnb-org/components/functions"
disabled = false

[[module.imports]]
path = "github.com/dnb-org/debug"
disabled = false

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"
disabled = false
