[module.hugoVersion]
extended = true
min = "0.56.0"

[[module.imports]]
path = "github.com/davidsneighbour/libraries/bootstrap5/v2"
disabled = false

[[module.imports]]
path = "github.com/davidsneighbour/hugo-functions"
disabled = false

[[module.imports]]
path = "github.com/davidsneighbour/hugo-debug"
disabled = false

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"
disabled = false
